# Generated by Django 3.2 on 2022-09-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cfdi',
        ),
    ]
