# Generated by Django 3.2 on 2022-09-19 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0003_transporteembarques_numero_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='embarque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='envios', to='transportista.embarque'),
        ),
        migrations.AlterField(
            model_name='enviodet',
            name='envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='enviosdet', to='transportista.envio'),
        ),
    ]
