# Generated by Django 3.2 on 2022-09-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0004_auto_20220919_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviodet',
            name='serie_cfdi',
        ),
        migrations.AddField(
            model_name='facturistaembarques',
            name='serie_cfdi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='or_estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='or_municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
