# Generated by Django 3.2 on 2022-09-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0005_auto_20220926_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enviodet',
            old_name='producto_sx',
            new_name='producto_id',
        ),
        migrations.RemoveField(
            model_name='enviodet',
            name='origen_det_sx',
        ),
    ]
