# Generated by Django 3.2 on 2022-09-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0006_auto_20220926_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturistaembarques',
            name='razon_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facturistaembarques',
            name='regimen_fiscal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
