# Generated by Django 3.2 on 2023-07-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0008_auto_20221031_1247'),
    ]

    operations = [
     
    ]
