# Generated by Django 3.2 on 2023-07-06 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0009_embarque_me_unidad_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrucciondeenvio',
            name='facturista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transportista.facturistaembarques'),
        ),
    ]
