# Generated by Django 3.2 on 2022-09-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceReplica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('central', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('server', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('data_base', models.CharField(max_length=255)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'data_source_replica',
                'managed': True,
            },
        ),
    ]
