# Generated by Django 3.2 on 2022-09-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_datasourcereplica_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entidad', models.CharField(blank=True, max_length=255, null=True)),
                ('folio', models.BigIntegerField()),
                ('serie', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'folio',
                'managed': True,
            },
        ),
    ]
